
on: [pull_request]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env:
      OPENAPI_KEY: ${{ secrets.OPENAPI_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Extract PR Data
      run: |
        echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
        echo "PR_BODY='$(echo "${{ github.event.pull_request.body }}" | sed ':a;N;$!ba;s/\n/\\n/g')'" >> $GITHUB_ENV


    - name: Run Python script
      run: python script.py
      env:
        PR_TITLE: ${{ env.PR_TITLE }}
        PR_BODY: ${{ env.PR_BODY }}
        PR_FILES: ${{ env.PR_DIFF }}

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add .
        git commit -m "Automated changes from GitHub Actions"