
on: [push, pull_request]

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Extract PR Data
      id: extract_pr_data
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          PR_DIFF=$(curl -sSL "${{ github.event.pull_request.diff_url }}")
          echo "PR_DIFF=${PR_DIFF}" >> $GITHUB_ENV
        fi
    - name: Run Python script
      run: python script.py
      env:
        PR_NUMBER: ${{ env.PR_NUMBER }}
        PR_TITLE: ${{ env.PR_TITLE }}
        PR_BODY: ${{ env.PR_BODY }}
        PR_USER: ${{ env.PR_USER }}
        PR_FILES: ${{ env.PR_FILES }}